name: Build CI

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    types: [rerequested]
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install python3-venv build-essential gettext
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: print versions
      run: python3 --version
    - name: setup venv
      run: make venv
    - name: lint
      run: make lint
    - name: build
      run: make cp dist
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: JEplayer
        path: CIRCUITPY
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: true
    - name: Upload Release Asset
      id: upload-release-asset 
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing its ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./JEplayer.zip
        asset_name: JEplayer.zip
        asset_content_type: application/zip
