name: Build CI

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    types: [rerequested]
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install python3-venv build-essential gettext
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: print versions
      run: python3 --version
    - name: setup venv
      run: make venv
    - name: lint
      run: make lint
    - name: build
      run: make cp
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: JEplayer
        path: CIRCUITPY

